# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d82a2026048799ef31781b71ac82c6e2c2b2810a64646c47a944fb27a296231ca0c71d205ea017bd519ed3e0d90f4542ccd2515cc416c278d39f459521b3836

test:
  secret_key_base: aba3770eafdc721ec01cc8b384f8b544cf09e3e63972e0eaa908778c99fddb5351f2f7e7878f13c56082530594703d73dfa5b99e329d9801b4620d75809d3ac1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
